# Site configuration
domain: "https://burthub.github.io/Blog/"
baseurl: "https://burthub.github.io/Blog/" # the subpath of your site, e.g. /blog/
url: "https://burthub.github.io/Blog/" # the base hostname & protocol for your site


basecss: 
# Theme specific configuration
title: burtblog
github_username: burt
exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
